version: '3.1'
services:
  nginx:
    image: "nginx:latest"
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - swellnetwork
    links:
      - swellnetwork
    volumes:
      - ./backend/nginx/staging/:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/letsencrypt:/var/www/letsencrypt:ro
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./backend/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  swellnetwork:
    image: node:16
    working_dir: /src
    command: "npm start"
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - NODE_ENV=development
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /tmp:/tmp
      - ./backend:/src
    restart: "always"
    ports:
      - "3000:3000"
